<?php

declare(strict_types=1);

namespace Ansien\FormToJsonBundle\Tests;

use Ansien\FormToJsonBundle\Tests\TestClasses\SuperFormType;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Button\ButtonTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Button\ResetTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Button\SubmitTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Choice\ChoiceTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Choice\CountryTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Choice\CurrencyTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Choice\EntityTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Choice\LanguageTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Choice\LocaleTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Choice\TimezoneTypeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\DateTime\BirthdayTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\DateTime\DateIntervalTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\DateTime\DateTimeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\DateTime\DateTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\DateTime\TimeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\DateTime\WeekTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\FormTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Group\CollectionTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Group\RepeatedTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Hidden\HiddenTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Other\CheckboxTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Other\FileTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Other\RadioTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\ColorTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\EmailTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\IntegerTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\MoneyTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\NumberTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\PasswordTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\PercentTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\RangeTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\SearchTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\TelTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\TextareaTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\TextTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\BuiltIn\Text\UrlTypeTransformer;
use Ansien\FormToJsonBundle\Transformer\Context\TransformerContext;
use Ansien\FormToJsonBundle\Transformer\Service\FormTransformer;

class TransformTest extends FormToJsonBundleTestCase
{
    private const expectedJson = <<<EOT
    {
       "id":"test",
       "name":"test",
       "label":null,
       "unique_block_prefix":"_test",
       "value":null,
       "required":true,
       "help":null,
       "compound":true,
       "method":"POST",
       "action":"",
       "attr":[

       ],
       "children":{
          "text":{
             "id":"test_text",
             "name":"text",
             "label":null,
             "unique_block_prefix":"_test_text",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "errors":[

             ]
          },
          "textarea":{
             "id":"test_textarea",
             "name":"textarea",
             "label":null,
             "unique_block_prefix":"_test_textarea",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "errors":[

             ]
          },
          "email":{
             "id":"test_email",
             "name":"email",
             "label":null,
             "unique_block_prefix":"_test_email",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "errors":[

             ]
          },
          "integer":{
             "id":"test_integer",
             "name":"integer",
             "label":null,
             "unique_block_prefix":"_test_integer",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "grouping":false,
                "rounding_mode":2
             },
             "errors":[

             ]
          },
          "money":{
             "id":"test_money",
             "name":"money",
             "label":null,
             "unique_block_prefix":"_test_money",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "currency":"EUR",
                "divisor":1,
                "grouping":false,
                "rounding_mode":6,
                "html5":false,
                "scale":2
             },
             "errors":[

             ]
          },
          "number":{
             "id":"test_number",
             "name":"number",
             "label":null,
             "unique_block_prefix":"_test_number",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "grouping":false,
                "html5":false,
                "input":"number",
                "scale":null,
                "rounding_mode":6
             },
             "errors":[

             ]
          },
          "password":{
             "id":"test_password",
             "name":"password",
             "label":null,
             "unique_block_prefix":"_test_password",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "always_empty":true
             },
             "errors":[

             ]
          },
          "percent":{
             "id":"test_percent",
             "name":"percent",
             "label":null,
             "unique_block_prefix":"_test_percent",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "rounding_mode":null,
                "html5":false,
                "scale":0,
                "symbol":"%",
                "type":"fractional"
             },
             "errors":[

             ]
          },
          "search":{
             "id":"test_search",
             "name":"search",
             "label":null,
             "unique_block_prefix":"_test_search",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "errors":[

             ]
          },
          "url":{
             "id":"test_url",
             "name":"url",
             "label":null,
             "unique_block_prefix":"_test_url",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":{
                "inputmode":"url"
             },
             "options":{
                "default_protocol":"http"
             },
             "errors":[

             ]
          },
          "range":{
             "id":"test_range",
             "name":"range",
             "label":null,
             "unique_block_prefix":"_test_range",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "errors":[

             ]
          },
          "tel":{
             "id":"test_tel",
             "name":"tel",
             "label":null,
             "unique_block_prefix":"_test_tel",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "errors":[

             ]
          },
          "color":{
             "id":"test_color",
             "name":"color",
             "label":null,
             "unique_block_prefix":"_test_color",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "html5":false
             },
             "errors":[

             ]
          },
          "choice":{
             "id":"test_choice",
             "name":"choice",
             "label":null,
             "unique_block_prefix":"_test_choice",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choices":[

                ],
                "choice_attr":null,
                "choice_filter":null,
                "choice_label":null,
                "choice_name":null,
                "choice_translation_domain":null,
                "choice_value":null,
                "expanded":false,
                "group_by":null,
                "multiple":false,
                "placeholder":null,
                "preferred_choices":[

                ]
             },
             "errors":[

             ]
          },
          "country":{
             "id":"test_country",
             "name":"country",
             "label":null,
             "unique_block_prefix":"_test_country",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choices":[

                ],
                "choice_attr":null,
                "choice_filter":null,
                "choice_label":null,
                "choice_name":null,
                "choice_translation_domain":false,
                "choice_value":null,
                "expanded":false,
                "group_by":null,
                "multiple":false,
                "placeholder":null,
                "preferred_choices":[

                ],
                "alpha3":false
             },
             "errors":[

             ]
          },
          "language":{
             "id":"test_language",
             "name":"language",
             "label":null,
             "unique_block_prefix":"_test_language",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choices":[

                ],
                "choice_attr":null,
                "choice_filter":null,
                "choice_label":null,
                "choice_name":null,
                "choice_translation_domain":false,
                "choice_value":null,
                "expanded":false,
                "group_by":null,
                "multiple":false,
                "placeholder":null,
                "preferred_choices":[

                ],
                "alpha3":false,
                "choice_self_translation":false
             },
             "errors":[

             ]
          },
          "locale":{
             "id":"test_locale",
             "name":"locale",
             "label":null,
             "unique_block_prefix":"_test_locale",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choices":[

                ],
                "choice_attr":null,
                "choice_filter":null,
                "choice_label":null,
                "choice_name":null,
                "choice_translation_domain":false,
                "choice_value":null,
                "expanded":false,
                "group_by":null,
                "multiple":false,
                "placeholder":null,
                "preferred_choices":[

                ],
                "choice_self_translation":null
             },
             "errors":[

             ]
          },
          "timezone":{
             "id":"test_timezone",
             "name":"timezone",
             "label":null,
             "unique_block_prefix":"_test_timezone",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choices":[

                ],
                "choice_attr":null,
                "choice_filter":null,
                "choice_label":null,
                "choice_name":null,
                "choice_translation_domain":false,
                "choice_value":null,
                "expanded":false,
                "group_by":null,
                "multiple":false,
                "placeholder":null,
                "preferred_choices":[

                ],
                "input":"string",
                "intl":false
             },
             "errors":[

             ]
          },
          "currency":{
             "id":"test_currency",
             "name":"currency",
             "label":null,
             "unique_block_prefix":"_test_currency",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choices":[

                ],
                "choice_attr":null,
                "choice_filter":null,
                "choice_label":null,
                "choice_name":null,
                "choice_translation_domain":false,
                "choice_value":null,
                "expanded":false,
                "group_by":null,
                "multiple":false,
                "placeholder":null,
                "preferred_choices":[

                ],
                "choice_translation_locale":null
             },
             "errors":[

             ]
          },
          "date":{
             "id":"test_date",
             "name":"date",
             "label":null,
             "unique_block_prefix":"_test_date",
             "value":{
                "year":"",
                "month":"",
                "day":""
             },
             "required":true,
             "help":null,
             "compound":true,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "days":[
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31
                ],
                "placeholder":{
                   "year":null,
                   "month":null,
                   "day":null
                },
                "format":2,
                "html5":true,
                "input":"datetime",
                "input_format":"Y-m-d",
                "model_timezone":null,
                "months":[
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12
                ],
                "view_timezone":null,
                "widget":"choice",
                "years":[
                   2016,
                   2017,
                   2018,
                   2019,
                   2020,
                   2021,
                   2022,
                   2023,
                   2024,
                   2025,
                   2026
                ]
             },
             "errors":[

             ]
          },
          "dateInterval":{
             "id":"test_dateInterval",
             "name":"dateInterval",
             "label":null,
             "unique_block_prefix":"_test_dateInterval",
             "value":{
                "years":"",
                "months":"",
                "days":""
             },
             "required":true,
             "help":null,
             "compound":true,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "days":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31
                ],
                "placeholder":{
                   "years":null,
                   "months":null,
                   "weeks":null,
                   "days":null,
                   "hours":null,
                   "minutes":null,
                   "seconds":null
                },
                "hours":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24
                ],
                "input":"dateinterval",
                "labels":{
                   "years":null,
                   "months":null,
                   "days":null,
                   "weeks":null,
                   "hours":null,
                   "minutes":null,
                   "seconds":null,
                   "invert":"Negative interval"
                },
                "minutes":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31,
                   32,
                   33,
                   34,
                   35,
                   36,
                   37,
                   38,
                   39,
                   40,
                   41,
                   42,
                   43,
                   44,
                   45,
                   46,
                   47,
                   48,
                   49,
                   50,
                   51,
                   52,
                   53,
                   54,
                   55,
                   56,
                   57,
                   58,
                   59,
                   60
                ],
                "months":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12
                ],
                "seconds":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31,
                   32,
                   33,
                   34,
                   35,
                   36,
                   37,
                   38,
                   39,
                   40,
                   41,
                   42,
                   43,
                   44,
                   45,
                   46,
                   47,
                   48,
                   49,
                   50,
                   51,
                   52,
                   53,
                   54,
                   55,
                   56,
                   57,
                   58,
                   59,
                   60
                ],
                "weeks":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31,
                   32,
                   33,
                   34,
                   35,
                   36,
                   37,
                   38,
                   39,
                   40,
                   41,
                   42,
                   43,
                   44,
                   45,
                   46,
                   47,
                   48,
                   49,
                   50,
                   51,
                   52
                ],
                "widget":"choice",
                "with_days":true,
                "with_hours":false,
                "with_invert":false,
                "with_minutes":false,
                "with_months":true,
                "with_seconds":false,
                "with_weeks":false,
                "with_years":true,
                "years":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31,
                   32,
                   33,
                   34,
                   35,
                   36,
                   37,
                   38,
                   39,
                   40,
                   41,
                   42,
                   43,
                   44,
                   45,
                   46,
                   47,
                   48,
                   49,
                   50,
                   51,
                   52,
                   53,
                   54,
                   55,
                   56,
                   57,
                   58,
                   59,
                   60,
                   61,
                   62,
                   63,
                   64,
                   65,
                   66,
                   67,
                   68,
                   69,
                   70,
                   71,
                   72,
                   73,
                   74,
                   75,
                   76,
                   77,
                   78,
                   79,
                   80,
                   81,
                   82,
                   83,
                   84,
                   85,
                   86,
                   87,
                   88,
                   89,
                   90,
                   91,
                   92,
                   93,
                   94,
                   95,
                   96,
                   97,
                   98,
                   99,
                   100
                ]
             },
             "errors":[

             ]
          },
          "dateTime":{
             "id":"test_dateTime",
             "name":"dateTime",
             "label":null,
             "unique_block_prefix":"_test_dateTime",
             "value":{
                "date":{
                   "year":"",
                   "month":"",
                   "day":""
                },
                "time":{
                   "hour":"",
                   "minute":""
                }
             },
             "required":true,
             "help":null,
             "compound":true,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choice_translation_domain":null,
                "date_format":null,
                "date_label":null,
                "date_widget":null,
                "days":null,
                "placeholder":null,
                "format":"yyyy-MM-dd'T'HH:mm:ss",
                "hours":null,
                "html5":true,
                "input":"datetime",
                "input_format":"Y-m-d H:i:s",
                "minutes":null,
                "model_timezone":null,
                "months":null,
                "seconds":null,
                "time_label":null,
                "time_widget":null,
                "view_timezone":null,
                "widget":null,
                "with_minutes":true,
                "with_seconds":false,
                "years":null
             },
             "errors":[

             ]
          },
          "time":{
             "id":"test_time",
             "name":"time",
             "label":null,
             "unique_block_prefix":"_test_time",
             "value":{
                "hour":"",
                "minute":""
             },
             "required":true,
             "help":null,
             "compound":true,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choice_translation_domain":{
                   "hour":false,
                   "minute":false,
                   "second":false
                },
                "placeholder":{
                   "hour":null,
                   "minute":null,
                   "second":null
                },
                "hours":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23
                ],
                "html5":true,
                "input":"datetime",
                "input_format":"H:i:s",
                "minutes":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31,
                   32,
                   33,
                   34,
                   35,
                   36,
                   37,
                   38,
                   39,
                   40,
                   41,
                   42,
                   43,
                   44,
                   45,
                   46,
                   47,
                   48,
                   49,
                   50,
                   51,
                   52,
                   53,
                   54,
                   55,
                   56,
                   57,
                   58,
                   59
                ],
                "model_timezone":null,
                "reference_date":null,
                "seconds":[
                   0,
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31,
                   32,
                   33,
                   34,
                   35,
                   36,
                   37,
                   38,
                   39,
                   40,
                   41,
                   42,
                   43,
                   44,
                   45,
                   46,
                   47,
                   48,
                   49,
                   50,
                   51,
                   52,
                   53,
                   54,
                   55,
                   56,
                   57,
                   58,
                   59
                ],
                "view_timezone":null,
                "widget":"choice",
                "with_minutes":true,
                "with_seconds":false
             },
             "errors":[

             ]
          },
          "birthday":{
             "id":"test_birthday",
             "name":"birthday",
             "label":null,
             "unique_block_prefix":"_test_birthday",
             "value":{
                "year":"",
                "month":"",
                "day":""
             },
             "required":true,
             "help":null,
             "compound":true,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "days":[
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12,
                   13,
                   14,
                   15,
                   16,
                   17,
                   18,
                   19,
                   20,
                   21,
                   22,
                   23,
                   24,
                   25,
                   26,
                   27,
                   28,
                   29,
                   30,
                   31
                ],
                "placeholder":{
                   "year":null,
                   "month":null,
                   "day":null
                },
                "format":2,
                "html5":true,
                "input":"datetime",
                "input_format":"Y-m-d",
                "model_timezone":null,
                "months":[
                   1,
                   2,
                   3,
                   4,
                   5,
                   6,
                   7,
                   8,
                   9,
                   10,
                   11,
                   12
                ],
                "view_timezone":null,
                "widget":"choice",
                "years":[
                   1901,
                   1902,
                   1903,
                   1904,
                   1905,
                   1906,
                   1907,
                   1908,
                   1909,
                   1910,
                   1911,
                   1912,
                   1913,
                   1914,
                   1915,
                   1916,
                   1917,
                   1918,
                   1919,
                   1920,
                   1921,
                   1922,
                   1923,
                   1924,
                   1925,
                   1926,
                   1927,
                   1928,
                   1929,
                   1930,
                   1931,
                   1932,
                   1933,
                   1934,
                   1935,
                   1936,
                   1937,
                   1938,
                   1939,
                   1940,
                   1941,
                   1942,
                   1943,
                   1944,
                   1945,
                   1946,
                   1947,
                   1948,
                   1949,
                   1950,
                   1951,
                   1952,
                   1953,
                   1954,
                   1955,
                   1956,
                   1957,
                   1958,
                   1959,
                   1960,
                   1961,
                   1962,
                   1963,
                   1964,
                   1965,
                   1966,
                   1967,
                   1968,
                   1969,
                   1970,
                   1971,
                   1972,
                   1973,
                   1974,
                   1975,
                   1976,
                   1977,
                   1978,
                   1979,
                   1980,
                   1981,
                   1982,
                   1983,
                   1984,
                   1985,
                   1986,
                   1987,
                   1988,
                   1989,
                   1990,
                   1991,
                   1992,
                   1993,
                   1994,
                   1995,
                   1996,
                   1997,
                   1998,
                   1999,
                   2000,
                   2001,
                   2002,
                   2003,
                   2004,
                   2005,
                   2006,
                   2007,
                   2008,
                   2009,
                   2010,
                   2011,
                   2012,
                   2013,
                   2014,
                   2015,
                   2016,
                   2017,
                   2018,
                   2019,
                   2020,
                   2021
                ]
             },
             "errors":[

             ]
          },
          "week":{
             "id":"test_week",
             "name":"week",
             "label":null,
             "unique_block_prefix":"_test_week",
             "value":null,
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "choice_translation_domain":{
                   "year":false,
                   "week":false
                },
                "placeholder":{
                   "year":null,
                   "week":null
                },
                "html5":true,
                "input":"array",
                "widget":"single_text",
                "years":[
                   2011,
                   2012,
                   2013,
                   2014,
                   2015,
                   2016,
                   2017,
                   2018,
                   2019,
                   2020,
                   2021,
                   2022,
                   2023,
                   2024,
                   2025,
                   2026,
                   2027,
                   2028,
                   2029,
                   2030,
                   2031
                ],
                "weeks":{
                   "1":1,
                   "2":2,
                   "3":3,
                   "4":4,
                   "5":5,
                   "6":6,
                   "7":7,
                   "8":8,
                   "9":9,
                   "10":10,
                   "11":11,
                   "12":12,
                   "13":13,
                   "14":14,
                   "15":15,
                   "16":16,
                   "17":17,
                   "18":18,
                   "19":19,
                   "20":20,
                   "21":21,
                   "22":22,
                   "23":23,
                   "24":24,
                   "25":25,
                   "26":26,
                   "27":27,
                   "28":28,
                   "29":29,
                   "30":30,
                   "31":31,
                   "32":32,
                   "33":33,
                   "34":34,
                   "35":35,
                   "36":36,
                   "37":37,
                   "38":38,
                   "39":39,
                   "40":40,
                   "41":41,
                   "42":42,
                   "43":43,
                   "44":44,
                   "45":45,
                   "46":46,
                   "47":47,
                   "48":48,
                   "49":49,
                   "50":50,
                   "51":51,
                   "52":52,
                   "53":53
                }
             },
             "errors":[

             ]
          },
          "checkbox":{
             "id":"test_checkbox",
             "name":"checkbox",
             "label":null,
             "unique_block_prefix":"_test_checkbox",
             "value":"1",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "false_values":[
                   null
                ],
                "value":"1"
             },
             "errors":[

             ]
          },
          "file":{
             "id":"test_file",
             "name":"file",
             "label":null,
             "unique_block_prefix":"_test_file",
             "value":"",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "multiple":false
             },
             "errors":[

             ]
          },
          "radio":{
             "id":"test_radio",
             "name":"radio",
             "label":null,
             "unique_block_prefix":"_test_radio",
             "value":"1",
             "required":true,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "false_values":[
                   null
                ],
                "value":"1"
             },
             "errors":[

             ]
          },
          "collection":{
             "id":"test_collection",
             "name":"collection",
             "label":null,
             "unique_block_prefix":"_test_collection",
             "value":null,
             "required":true,
             "help":null,
             "compound":true,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "allow_add":true,
                "allow_delete":false,
                "delete_empty":false,
                "entry_options":{
                   "block_name":"entry"
                },
                "prototype":true,
                "prototype_data":null,
                "prototype_name":"__name__"
             },
             "errors":[

             ]
          },
          "repeated":{
             "id":"test_repeated",
             "name":"repeated",
             "label":null,
             "unique_block_prefix":"_test_repeated",
             "value":{
                "first":null,
                "second":null
             },
             "required":true,
             "help":null,
             "compound":true,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "options":{
                "first_name":"first",
                "first_options":[

                ],
                "options":[

                ],
                "second_name":"second",
                "second_options":[

                ]
             },
             "errors":[

             ]
          },
          "hidden":{
             "id":"test_hidden",
             "name":"hidden",
             "label":null,
             "unique_block_prefix":"_test_hidden",
             "value":"",
             "required":false,
             "help":null,
             "compound":false,
             "method":"POST",
             "action":"",
             "attr":[

             ],
             "errors":[

             ]
          },
          "button":{
             "id":"test_button",
             "name":"button",
             "label":null,
             "unique_block_prefix":"_test_button",
             "value":null,
             "required":null,
             "help":null,
             "compound":null,
             "method":null,
             "action":null,
             "attr":[

             ],
             "errors":[

             ]
          },
          "reset":{
             "id":"test_reset",
             "name":"reset",
             "label":null,
             "unique_block_prefix":"_test_reset",
             "value":null,
             "required":null,
             "help":null,
             "compound":null,
             "method":null,
             "action":null,
             "attr":[

             ],
             "errors":[

             ]
          },
          "submit":{
             "id":"test_submit",
             "name":"submit",
             "label":null,
             "unique_block_prefix":"_test_submit",
             "value":null,
             "required":null,
             "help":null,
             "compound":null,
             "method":null,
             "action":null,
             "attr":[

             ],
             "options":{
                "validate":true
             },
             "errors":[

             ]
          }
       },
       "errors":[

       ]
    }
    EOT;

    public function test(): void
    {
        $form = $this->factory->createNamedBuilder('test', SuperFormType::class)->getForm();

        $transformerContext = new TransformerContext();
        $transformer = new FormTransformer($transformerContext);

        // Default
        $transformerContext->addTransformer(new FormTypeTransformer($this->translator, $transformer));
        // Text
        $transformerContext->addTransformer(new TextTypeTransformer($this->translator));
        $transformerContext->addTransformer(new TextareaTypeTransformer($this->translator));
        $transformerContext->addTransformer(new EmailTypeTransformer($this->translator));
        $transformerContext->addTransformer(new IntegerTypeTransformer($this->translator));
        $transformerContext->addTransformer(new MoneyTypeTransformer($this->translator));
        $transformerContext->addTransformer(new NumberTypeTransformer($this->translator));
        $transformerContext->addTransformer(new PasswordTypeTransformer($this->translator));
        $transformerContext->addTransformer(new PercentTypeTransformer($this->translator));
        $transformerContext->addTransformer(new SearchTypeTransformer($this->translator));
        $transformerContext->addTransformer(new UrlTypeTransformer($this->translator));
        $transformerContext->addTransformer(new RangeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new TelTypeTransformer($this->translator));
        $transformerContext->addTransformer(new ColorTypeTransformer($this->translator));
        // Choice
        $transformerContext->addTransformer(new ChoiceTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new EntityTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new CountryTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new LanguageTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new LocaleTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new TimezoneTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new CurrencyTypeTypeTransformer($this->translator));
        // DateTime
        $transformerContext->addTransformer(new DateTypeTransformer($this->translator));
        $transformerContext->addTransformer(new DateIntervalTypeTransformer($this->translator));
        $transformerContext->addTransformer(new DateTimeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new TimeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new BirthdayTypeTransformer($this->translator));
        $transformerContext->addTransformer(new WeekTypeTransformer($this->translator));
        // Other
        $transformerContext->addTransformer(new CheckboxTypeTransformer($this->translator));
        $transformerContext->addTransformer(new FileTypeTransformer($this->translator));
        $transformerContext->addTransformer(new RadioTypeTransformer($this->translator));
        // Group
        $transformerContext->addTransformer(new CollectionTypeTransformer($this->translator, $transformer));
        $transformerContext->addTransformer(new RepeatedTypeTransformer($this->translator, $transformer));
        // Hidden
        $transformerContext->addTransformer(new HiddenTypeTransformer($this->translator));
        // Button
        $transformerContext->addTransformer(new ButtonTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new ResetTypeTypeTransformer($this->translator));
        $transformerContext->addTransformer(new SubmitTypeTypeTransformer($this->translator));

        $result = $transformer->transform($form);

        self::assertEquals(json_encode(json_decode(self::expectedJson)), json_encode($result));
    }
}
